class Contract:
    C_TOKEN_REFRESH = "C_TOKEN_REFRESH"
    C_FORMING_PARITY_GROUP = "C_FORMING_PARITY_GROUP"
    C_HIGH_CAPACITY_DISK_WRITE = "C_HIGH_CAPACITY_DISK_WRITE"
    C_LOW_CAPACITY_DISK_WRITE = "C_LOW_CAPACITY_DISK_WRITE"
    C_PENDING_PARITY_GROUP = "C_PENDING_PARITY_GROUP"
    C_TOKEN_REFRESH = "C_TOKEN_REFRESH"

    S_SEND_ACK = "S_SEND_ACK"
    S_SERVER_COUNT = "S_SERVER_COUNT"
